### Variables
@baseUrl = {{$dotenv API_BASE_URL}}
@contentType = application/json

### Register a new user
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
    "username": "testuser4",
    "password": "Test123!",
    "first_name": "Test",
    "last_name": "User",
    "birth_date": "1990-01-01"
}

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "username": "testuser4",
    "password": "Test123!"
}

### Refresh token
POST {{baseUrl}}/auth/refresh
Content-Type: {{contentType}}
Cookie: refresh_token={{login.response.headers.Set-Cookie.[1]}}

### Logout
POST {{baseUrl}}/auth/logout
Content-Type: {{contentType}}
Cookie: access_token={{login.response.headers.Set-Cookie}}; refresh_token={{login.response.headers.Set-Cookie.[1]}}
