### Variables
@baseUrl = {{$dotenv API_BASE_URL}}
@contentType = application/json

### Login as user
# @name userLogin
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "username": "testuser4",
    "password": "Test123!"
}

### Login as admin
# @name adminLogin
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "username": "admin",
    "password": "Admin123!"
}

### Complaint Feedback Tests

### Create and manage feedback for a complaint
POST {{baseUrl}}/complaints/1/feedback
Content-Type: {{contentType}}
Authorization: Bearer {{adminLogin.response.body.data.token}}

{
    "content": "This is a test feedback for the complaint"
}

### Get all feedback for a complaint
GET {{baseUrl}}/complaints/1/feedback
Content-Type: {{contentType}}
Authorization: Bearer {{userLogin.response.body.data.token}}

### Update feedback
PUT {{baseUrl}}/complaints/1/feedback/1
Content-Type: {{contentType}}
Authorization: Bearer {{adminLogin.response.body.data.token}}

{
    "content": "This is an updated test feedback"
}

### Delete feedback
DELETE {{baseUrl}}/complaints/1/feedback/1
Content-Type: {{contentType}}
Authorization: Bearer {{adminLogin.response.body.data.token}}

### Suggestion Feedback Tests

### Create and manage feedback for a suggestion
POST {{baseUrl}}/suggestions/1/feedback
Content-Type: {{contentType}}
Authorization: Bearer {{adminLogin.response.body.data.token}}

{
    "content": "This is a test feedback for the suggestion"
}

### Get all feedback for a suggestion
GET {{baseUrl}}/suggestions/1/feedback
Content-Type: {{contentType}}
Authorization: Bearer {{userLogin.response.body.data.token}}

### Update feedback
PUT {{baseUrl}}/suggestions/1/feedback/15
Content-Type: {{contentType}}
Authorization: Bearer {{adminLogin.response.body.data.token}}

{
    "content": "This is an updated test feedback"
}

### Delete feedback
DELETE {{baseUrl}}/suggestions/1/feedback/15
Content-Type: {{contentType}}
Authorization: Bearer {{adminLogin.response.body.data.token}}