### Variables
@baseUrl = {{$dotenv API_BASE_URL}}
@contentType = application/json

### Login (needed for authentication)
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "username": "testuser5",
    "password": "Test123!"
}

### Get user profile
GET {{baseUrl}}/users/me
Content-Type: {{contentType}}
Cookie: access_token={{login.response.headers.Set-Cookie}}

### Update profile
PUT {{baseUrl}}/users/me
Content-Type: {{contentType}}
Cookie: access_token={{login.response.headers.Set-Cookie}}

{
    "firstName": "Updated",
    "lastName": "User",
    "birthDate": "1990-01-01",
    "photoPath": "/uploads/profile/new-photo.jpg"
}

### Update profile with invalid fields (should fail)
PUT {{baseUrl}}/users/me
Content-Type: {{contentType}}
Cookie: access_token={{login.response.headers.Set-Cookie}}

{
    "firstName": "Updated",
    "lastName": "User",
    "birthDate": "1990-01-01",
    "username": "hacker",
    "password": "hack123",
    "created_at": "2024-01-01"
}

### Update password
PUT {{baseUrl}}/users/password
Content-Type: {{contentType}}
Cookie: access_token={{login.response.headers.Set-Cookie}}

{
    "current_password": "NewTest123!",
    "new_password": "NewTest1234!"
}

### Delete account with wrong password (should fail)
DELETE {{baseUrl}}/users/me
Content-Type: {{contentType}}
Cookie: access_token={{login.response.headers.Set-Cookie}}

{
    "password": "WrongPassword123!"
}

### Delete account with correct password
DELETE {{baseUrl}}/users/me
Content-Type: {{contentType}}
Cookie: access_token={{login.response.headers.Set-Cookie}}

{
    "password": "Test123!"
}

### Verify account is deleted - try to login (should fail)
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "username": "testuser5",
    "password": "Test123!"
}

### Verify account is deleted - try to get profile (should fail)
GET {{baseUrl}}/users/me
Content-Type: {{contentType}}
Cookie: access_token={{login.response.headers.Set-Cookie}}