### Variables
@baseUrl = {{$dotenv API_BASE_URL}}
@contentType = application/json

### Login as admin
# @name adminLogin
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "username": "admin",
    "password": "Admin123!"
}

### User CRUD

### Create user
POST {{baseUrl}}/users
Content-Type: {{contentType}}
Authorization: Bearer {{adminLogin.response.body.data.token}}

{
    "username": "testuser",
    "password": "Test123!",
    "email": "test@example.com",
    "firstName": "Test",
    "lastName": "User",
    "role": "user"
}

### Get users
GET {{baseUrl}}/users
Content-Type: {{contentType}}
Authorization: Bearer {{adminLogin.response.body.data.token}}

### Update user
PUT {{baseUrl}}/users/1
Content-Type: {{contentType}}
Authorization: Bearer {{adminLogin.response.body.data.token}}

{
    "firstName": "Updated",
    "lastName": "User"
}

### Delete user
DELETE {{baseUrl}}/users/1
Content-Type: {{contentType}}
Authorization: Bearer {{adminLogin.response.body.data.token}}