### Variables
@baseUrl = {{$dotenv API_BASE_URL}}
@contentType = application/json

### Login (needed for authentication)
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "username": "testuser3",
    "password": "Test123!"
}

### Get user profile
GET {{baseUrl}}/users/profile
Content-Type: {{contentType}}
Cookie: access_token={{login.response.headers.Set-Cookie}}

### Update password
PUT {{baseUrl}}/users/password
Content-Type: {{contentType}}
Cookie: access_token={{login.response.headers.Set-Cookie}}

{
    "current_password": "NewTest123!",
    "new_password": "NewTest1234!"
} 